# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do




    # 测试环境
  desc "以 AMS_DEV 测试环境 方式打包并上传到 蒲公英"  
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
    # update_app_identifier(
    #   plist_path:"PadParents/Resources/PadParentsDEV-Info.plist",
    #     app_identifier: "com.pxjy.padParentsDev" # The App Identifier
    #   )

    
    testApp("Project")
  end







  lane :appstore do

    sigh(
      # 指定输出的文件夹地址
      output_path: "./archive/Project",
    )

    puts "以 app-store 方式打包"
    gym(
      # Method used to export the archive. Valid values are:
      # app-store, validation, ad-hoc, package, enterprise, development, developer-id and mac-application
      # 指定打包所使用的输出方式 (可选: app-store, package, ad-hoc, enterprise, development)
      export_method: "app-store",
      # 指定项目的 scheme 名称
      scheme: "Project",
      # 指定输出的文件夹地址
      output_directory: "./archive/appStore/" + Time.new.strftime("%Y-%m-%d-%H:%M:%S"),
      # 指定打包方式 (可选: Release, Debug)
      configuration: "Release",
      output_name: "caidaoApp_appStore.ipa"
    )

    puts "上传 ipa 包到 iTunes Connect"
    deliver(
      # 跳过截图上传
      skip_screenshots: true,
      # 跳过元数据上传
      skip_metadata: true,
      # 跳过审核直接上传
      force: true
    )

  end




  def testApp(scheme)
    gym(
        # 指定打包所使用的输出方式 (可选: app-store, package, ad-hoc, enterprise, development)
        export_method: "development",
        # configuration: "Release",
        # 指定项目的 scheme 名称
        scheme: scheme,
        workspace: "Project.xcworkspace",
        # 指定输出的文件夹地址
        output_directory: "./archive/"+ scheme +"/" + Time.new.strftime("%Y-%m-%d-%H:%M:%S"),
        output_name: scheme + ".ipa",
      )

      sigh(
        # 指定输出的文件夹地址
        output_path: "./archive/"+scheme,
        # app_identifier: "com.pxjy.padParentsDev"
      )
  end


end
